// <auto-generated />
using System;
using CapstoneProjectAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CapstoneProjectAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714052857_AddAiSummaryToDocumentVersion")]
    partial class AddAiSummaryToDocumentVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CapstoneProjectAPI.Models.ApprovalAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<int>("ApproverUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentVersionId")
                        .HasColumnType("integer");

                    b.Property<int?>("ForwardedToDepartmentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentVersionId");

                    b.HasIndex("ForwardedToDepartmentId");

                    b.ToTable("ApprovalActions");
                });

            modelBuilder.Entity("CapstoneProjectAPI.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<int?>("DocumentVersionId")
                        .HasColumnType("integer");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentVersionId");

                    b.HasIndex("PerformedByUserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CapstoneProjectAPI.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CapstoneProjectAPI.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentApproverUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DocumentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("TargetDepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CurrentApproverUserId");

                    b.HasIndex("TargetDepartmentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("CapstoneProjectAPI.Models.DocumentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("DocumentVersions");
                });

            modelBuilder.Entity("CapstoneProjectAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CapstoneProjectAPI.Models.ApprovalAction", b =>
                {
                    b.HasOne("CapstoneProjectAPI.Models.User", "ApproverUser")
                        .WithMany("ApprovalActions")
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapstoneProjectAPI.Models.Document", "Document")
                        .WithMany("ApprovalActions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapstoneProjectAPI.Models.DocumentVersion", "DocumentVersion")
                        .WithMany("ApprovalActions")
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CapstoneProjectAPI.Models.Department", "ForwardedToDepartment")
                        .WithMany()
                        .HasForeignKey("ForwardedToDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApproverUser");

                    b.Navigation("Document");

                    b.Navigation("DocumentVersion");

                    b.Navigation("ForwardedToDepartment");
                });

            modelBuilder.Entity("CapstoneProjectAPI.Models.AuditLog", b =>
                {
                    b.HasOne("CapstoneProjectAPI.Models.Document", "Document")
                        .WithMany("AuditLogs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CapstoneProjectAPI.Models.DocumentVersion", "DocumentVersion")
                        .WithMany("AuditLogs")
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CapstoneProjectAPI.Models.User", "PerformedByUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("DocumentVersion");

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("CapstoneProjectAPI.Models.Document", b =>
                {
                    b.HasOne("CapstoneProjectAPI.Models.User", "CreatedByUser")
                        .WithMany("CreatedDocuments")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapstoneProjectAPI.Models.User", "CurrentApprover")
                        .WithMany()
                        .HasForeignKey("CurrentApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CapstoneProjectAPI.Models.Department", "TargetDepartment")
                        .WithMany()
                        .HasForeignKey("TargetDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("CurrentApprover");

                    b.Navigation("TargetDepartment");
                });

            modelBuilder.Entity("CapstoneProjectAPI.Models.DocumentVersion", b =>
                {
                    b.HasOne("CapstoneProjectAPI.Models.Document", "Document")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapstoneProjectAPI.Models.User", "UploadedByUser")
                        .WithMany("UploadedVersions")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("CapstoneProjectAPI.Models.User", b =>
                {
                    b.HasOne("CapstoneProjectAPI.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapstoneProjectAPI.Models.User", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("CapstoneProjectAPI.Models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CapstoneProjectAPI.Models.Document", b =>
                {
                    b.Navigation("ApprovalActions");

                    b.Navigation("AuditLogs");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CapstoneProjectAPI.Models.DocumentVersion", b =>
                {
                    b.Navigation("ApprovalActions");

                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("CapstoneProjectAPI.Models.User", b =>
                {
                    b.Navigation("ApprovalActions");

                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedDocuments");

                    b.Navigation("Subordinates");

                    b.Navigation("UploadedVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
